export const VideoCardAPI = [
  {
    videoImg: "/img/video_card_images/01.jpg",
    videoTitle: "Let's build Instagram 2.0 with REACT.JS! ",
    channelImg: "/img/video_card_channel_imgs/01.jpg",
    channelName: "Sonny Sangha",
    videoViews: "99K views",
    timeStamp: "2 weeks ago",
  },
  {
    videoImg: "/img/video_card_images/02.jpg",
    videoTitle: "Let's Build a Full-Stack AMAZON Clone ",
    channelImg: "/img/video_card_channel_imgs/02.jpg",
    channelName: " Clever Programmer",
    videoViews: "753K views",
    timeStamp: "1 years ageo",
  },
  {
    videoImg: "/img/video_card_images/03.jpg",
    videoTitle: "Difference between Library vs Framework | লাইব্রেরি বনাম",
    channelImg: "/img/video_card_channel_imgs/03.jpg",
    channelName: "procoder bd",
    videoViews: "5.9k views",
    timeStamp: "8 month ago",
  },
  {
    videoImg: "/img/video_card_images/04.jpg",
    videoTitle:
      "React Project Tutorial - Quiz Application with Firebase - Part 1",
    channelImg: "/img/video_card_channel_imgs/04.jpg",
    channelName: "Learn with Sumit",
    videoViews: "7.4k views",
    timeStamp: "1 month ago",
  },
  {
    videoImg: "/img/video_card_images/05.jpg",
    videoTitle: "The Basics of Mechanical Keyboard ft. Keychron K3",
    channelImg: "/img/video_card_channel_imgs/05.jpg",
    channelName: "Sohag360",
    videoViews: "158K views",
    timeStamp: "1 month ago",
  },
  {
    videoImg: "/img/video_card_images/06.jpg",
    videoTitle: "Next.JS Tutorial For Beginners In Hindi #1",
    channelImg: "/img/video_card_channel_imgs/06.jpg",
    channelName: "thapa technical",
    videoViews: "17K views",
    timeStamp: "1 month ago",
  },
  {
    videoImg: "/img/video_card_images/07.jpg",
    videoTitle: "Corsair K60 RGB pro SE mechanical gaming keyboard",
    channelImg: "/img/video_card_channel_imgs/07.jpg",
    channelName: "hardware sentinels",
    videoViews: "3K views",
    timeStamp: "2 months ago",
  },
  {
    videoImg: "/img/video_card_images/08.jpg",
    videoTitle:
      "মেসেঞ্জার ট্রিক !!! টাইপ না করেই অটোমেটিক আনলিমিটেড মেসেজ পাঠাও",
    channelImg: "/img/video_card_channel_imgs/08.jpg",
    channelName: "jhankar mahbub",
    videoViews: "74k views",
    timeStamp: "1 year ago",
  },
  {
    videoImg: "/img/video_card_images/09.jpg",
    videoTitle: "Beautiful Dashboard UI Design - Adobe XD UI Design Tutorial",
    channelImg: "/img/video_card_channel_imgs/09.jpg",
    channelName: "Dev Ed",
    videoViews: "38k views",
    timeStamp: "3 month ago",
  },
  {
    videoImg: "/img/video_card_images/10.jpg",
    videoTitle:
      "Build A Calculator With JavaScript Tutorial + JavaScript Project",
    channelImg: "/img/video_card_channel_imgs/10.jpg",
    channelName: "hablu programmer",
    videoViews: "1.1k views",
    timeStamp: "1 month ago",
  },
  {
    videoImg: "/img/video_card_images/11.jpg",
    videoTitle: "Give Your Desktop The Wow Factor | Elegant Clean Look",
    channelImg: "/img/video_card_channel_imgs/11.jpg",
    channelName: "link vegas",
    videoViews: "1.4m views",
    timeStamp: "6 month",
  },
  {
    videoImg: "/img/video_card_images/12.jpg",
    videoTitle: "15+ Terminal Commands Every Developer Must Know",
    channelImg: "/img/video_card_channel_imgs/12.jpg",
    channelName: "Web Dev Simplified",
    videoViews: "39k views",
    timeStamp: "5 month ago",
  },
];
